### ISSUE TITLE
-h, -v フラグを使ったときに正常終了しない

### ISSUE THREAD

**Issue by 0918nobita** [iigura/Paraphrase#6]
「`-h`, `-v` フラグを使用した場合に exit code が `255` になるため、シェルにおいて異常終了として扱われてしまう」という不具合を発見しました。

```zsh
% ./para -h
Usage: para [-ehknqtv] [--thread]  [program-file] [program-code]
  -h (--help)      print help.
  -v (--version)   print version.
  --thread N       set maximum thread. N should be a positive integer.
  -e (--eval) S    evaluate the string S before executing the given script file.
  -E (--eval-and-exit) S  evaluate the string S and exit.
  -q (--quiet)     suppress prompt and 'ok'. (equivalent to -nk)
  -n (--noprompt)  suppress prompt.
  -k (--nook)      suppress 'ok' message (no ok)
  -t (--time)      display spent time.
Ex) para FizzBuzz.pp 1 20 for+ i FizzBuzz . next cr
% echo $?
255
% ./para -v
Paraphrase 0.94.0  Copyright (C) 2018-2021 Koji Iigura
% echo $?
255
% ./para -v && echo "This should be printed"
Paraphrase 0.94.0  Copyright (C) 2018-2021 Koji Iigura
```

これは、`/src/lang/para.cpp` の `parseOption` 関数において `-h`, `-v` フラグを指定されていることが異常系として (オプションの取得に失敗した場合や不正な値を与えられていた場合と同じように) 扱われていることに起因していると思われます。

https://github.com/iigura/Paraphrase/blob/70e6ea609c62661e368122f2b0095e184294d9c8/src/lang/para.cpp#L140

https://github.com/iigura/Paraphrase/blob/70e6ea609c62661e368122f2b0095e184294d9c8/src/lang/para.cpp#L269-L270

## 実行環境

- Device: MacBook Pro (15-inch, 2017)
- OS: macOS Catalina v10.15.7
- Shell: Zsh

## リビジョン

70e6ea609c62661e368122f2b0095e184294d9c8

**Comment by iigura** [comment]
問題提起ありがとうございます。
オプション v と h については、それらを表示し・正常終了するべき理由が見当たらなかったので、そのように実装したと記憶しています（このあたりは記憶が曖昧です）。

他の言語処理系がどのようになっているか調べてみました。
ruby と python では、いずれのオプションでも正常終了（終了コード 0）を返していました。
lua については、バージョン表示は正常終了（終了コード 0）を、ヘルプ情報表示は終了コード 1 を返していました。

オプション v と h で exit code を 255 とするのが「不具合」なのかどうか、判断が付かない状況です。
さてどうしたものでしょうか。

オプション v については、有名どころの ruby, python, lua にならい終了コードを 0 にしても良いのかなと思います（技術的な根拠はないです。日和見）。

オプション h については、さてどうしたものか、というところです。
ご意見いただければ助かります。

**Comment by 0918nobita** [comment]
実際の利用シーンを考えてみます。

GitHub Actions, Travis CI, Circle CI のような CI 環境では、ジョブの準備段階でログを残す目的で処理系がオプション v 付きで実行されることが多いと思います。そういう状況で exit code が 0 以外になってしまうと、後続のタスクが実行されずにジョブ全体が失敗した扱いになり都合が悪いです。そのためオプション v についてはやはり exit code を 0 にするのが良さそうです。

オプション h については確かに微妙なところではありますが、そもそも「ヘルプ情報を表示すること」を「コマンドの失敗」として扱うのは不自然な気がします。あえて失敗扱いするメリットもなさそうです。なのでオプション h についても同様に exit code を 0 にするのが良いと思います。

**Comment by iigura** [comment]
オプション v の件、了解しました。
オプション h の場合は、ヘルプを表示させつつ、次の処理を行う ー という状況が想像できないです。
むしろ、積極的に止めるべきなのでは？とさえ感じてしまいます。
ただ、多くの処理系がヘルプを表示させつつ exit code 0 なんですよね（なにか理由があるのでしょうか。気になります）。

ただまあ、このあたり、あまりこだわらずにエイヤっとオプション v も h も exit code を 0 にしちゃっても良いのかもしれません。もし気になるようでしたらプルリク出していただければ対応します。

**Comment by 0918nobita** [comment]
プルリク投げました。プルリクのほうがマージされると自動でこの issue がクローズされるように設定してあります。

**Comment by iigura** [comment]
プルリク拝見しました。
マージするようにします。

今回追加していただいた列挙型 "Command" ですが、名前が漠然としているので ParseResult など、列挙名を変更すると思います（ParseResult_CommandLineOptions とか？←うーん、長い！ ParseResultCLOs とか略しても良いのかもしれません）。
